import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import home from '/public/home.png'
import { AiOutlineCaretRight } from 'react-icons/ai';
import Works from './Works'
import Reviews from './Reviews'
import Choose from './Choose'
import Related from './Related'
import Navbar from './Navbar'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >
        <div >
          <Image className={styles.homeImage} src={home}/>
          <div className={styles.text}>
          <h1>Electrician Services</h1>
          <p>Expert Diagnosing</p>
          <hr/>
          </div>
          <div className={styles.content}>
            <p className={styles.tbg}>What are you looking for?</p>
            <div className={styles.services}>
              <button>Services / Repair <AiOutlineCaretRight/></button>
              <button>Installation <AiOutlineCaretRight/></button>
              <button>Uninstallation <AiOutlineCaretRight/></button>
              <button>Electricity Breakdown<AiOutlineCaretRight/></button>

            </div>
            

          </div>
          <div className={styles.price}>
              <p className={styles.tbg}>View Prices</p>
            </div>
        </div>
        <Works/>
        <Reviews/>
        <Choose/>
        <Related/>
        <Navbar/>
      </main>
    </>
  )
}
